sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: AexpAe3W77L+dfTO8TM+yY+1iL3y9r4/lab78jePRszDx3xf34oAqXwhewCkZwWViEIXMuRhQ1Msr38ySHoN76+QLP4wwlTSlJZjRzVc02CUcqupGvahb2m6w7qkSwU2qCpf/2KTILZNvaX+XiZUXPdMZgsHsys6bO2Zob/NIeiNfVpfF+za9goK+6lIu03hL7c6Kj1CZVjW52ZgKXRX39JTMApWJQt5KEwKA2m5Labhn6ooWpnikQ01/xbxsj0nM2hLKP/8+k1RNX3D2RDTxThm4xiuh/Ezkw80D3woraqU78hnJCqT2Lgnv8r7LfBuMB9Ew1fJfGINbNsx6EZUgr7B3baBSLWbRkLii/4L+5HNC3jMGYoR4Nu1b0yMvM2T51BqPYa1vNvxkctPxfT8SuiNjeYn+kHf5DkCbUJSVB3iD3qmswEojvnhJJJBKLSkKLIfHL0Nx8GA5xRfkgIHZ1DE61z0l/YgRblZV3gywWH5iVAs5SdS0WF7fzHetGUcbKVUmkEARS8tpVdzNY0OFPjw3wyylJbErzc/GbXMoHFfdX9U/5fajU4tLsWDF3qZbUpXcMGX3HWL+VpQ9VfE9yiUTNqZgHX1Fd9lr3XciBdMyWkeRezBinCKHHGzB6Jk97AKBZMTkl7Z8k/MqyWVYGZX58OkoO/lKOPNF2XNMhE=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: wM4xsp5eyOfySKjT50fcKMuVNek1ZcuEk7x6CoxKJaXjbJWcyoKM5ktGGBxISoDPri8kz4YzSh2vLWeLYG1bG8qrbX59r3zbCJjXGBofEsKuOhNZ2uyISc0OHXTxFrnyPDZnRDdHoOZNcFeL1y4mkVZnPDsDcWN4ZZPxQOOHDRnlvwhYEU93A839gdYYpQoSOqCauivHnB3SGtPMr7zVwEhoo8/ZSru+jGNsFzvZ4MIs3ddj1/gGuzg4jKxc/XFFJ3BPBvYSeTDji3kqo/TGvMWrZvDJcDfTZloMJRP3MPpI+/ivfgQDnA9clcZLYaUUhIx3+Iip/dq4ty/ZqPhU0xa4TLxQbOKGlKkd8xogOvtmPn9zAXb8pJBEJaLeUyRurO+ZM6l4vztA1ZD4YT2Eutm2UoVT1lq/dDc/D3ZPkkh9srdyR8MGacV3sb20TEo/uXAyEUUrYj7fFN6HA9LELqetaYBoH84gYfa/g658CeO607Ac7NmL+7jXJBaCsvBGXePWOXWwpqjM+dTjWFXJztr58YpH5sHJXJVFX6jKRTtOhPfWPnE3VsQjgii5Thq0TIEXvAr7qY4yt+7xwqsBTXwyIPiN+FhyqlttN8ZqVoIcFZfGDwa0X2rTo2k6//A29bZpBBBT+SQlh2OHFytQxR9I83zu4FiYAalEEb4seXo=
